/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.4/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:28.2-jre")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

application {
    // Define the main class for the application.
    mainClassName = "init.build.App"
}

open abstract class SomeTask : DefaultTask() {
    @get:OutputDirectory
    abstract val destination: DirectoryProperty
    
    @get:InputFiles
    abstract val source: DirectoryProperty

    @get:javax.inject.Inject
    abstract val fileOperations: FileSystemOperations

    @TaskAction
    fun copyIt() {
        fileOperations.copy { 
            from(source)
            into(destination)
        }
    }
}

tasks.register("someTask", SomeTask::class.java) {
    source.set(layout.projectDirectory.dir("src"))
    destination.set(layout.projectDirectory.dir(providers.systemProperty("someDestination")))
}
